
'use client'
 
import { Provider } from "react-redux";
import { store } from "@/redux/store";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'; //prevent hydration issue 


// export const metadata = {
//   title: "My Next App",
//   description: "Generated by Next.js",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
          <AppRouterCacheProvider>
    {/* <Navbar/> */}
       <Provider store={store}>
          {children}
        </Provider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
